name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create dist folder
        run: mkdir -p dist

      - uses: Platane/snk@v3
        id: snake-light
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: dist/github-snake.svg

      - uses: Platane/snk@v3
        id: snake-dark
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: dist/github-snake-dark.svg
          palette: github-dark

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
          keep_history: false
          allow_empty_commit: true
          jekyll: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
