# Nome da Action
name: Snake Game

# Agenda para rodar automaticamente (a cada 5 horas) + opção manual
on:
  schedule:
    - cron: "0 */5 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      # Clona o repositório
      - uses: actions/checkout@v3

      # Gera a cobrinha
      - uses: Platane/snk@v3
        with:
          github_user_name: Tjaos
          outputs: |
            dist/github-contribution-grid-snake.svg

      # Faz o commit na branch output
      - name: Commit and Push Snake
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
